
version: '3'

services:

  db__local:
    container_name: db__local
    image: postgres:12.5
    env_file: .env
    environment:
      POSTGRES_DB: data_platform
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # alternative way to running things on host
  main__local:
    container_name: main__local
    env_file: .env
    build:
      context: .
    depends_on:
      - db__local
    working_dir: /data_platform
    volumes:
      - ~/.aws:/root/.aws:ro # map credentials to be used by boto3, read-only
      - ./:/data_platform:ro # map data platform for access to scripts, read-only