"""Added incoming table

Revision ID: f0e89284baed
Revises: 
Create Date: 2022-01-05 09:45:55.805520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f0e89284baed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incoming',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('deleted', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=500), nullable=False),
    sa.Column('s3_prefix', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('partition', sa.VARCHAR(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incoming')
    # ### end Alembic commands ###
